[project]
name = "tme310_homework"
version = "0.1.0"
description = "Homework template for TME 310"
dependencies = [
    "marimo",
    "numpy",
    "scipy",
    "matplotlib"
]
requires-python = ">=3.10"