name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: notebook tests
      id: notebook_tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NOTEBOOK_TESTS_RESULTS: "${{steps.notebook_tests.outputs.result}}"
      with:
        runners: notebook_tests
    - name: Replace autograding results section in README.md
      run: |
        RESULTS_SECTION="---\n## Latest Autograding Test Results\n\n${{ steps.notebook_tests.outputs.result }}\n"
        # If the marker exists, replace the section; otherwise, append at the end
        if grep -q "## Latest Autograding Test Results" README.md; then
          awk -v new_section="$RESULTS_SECTION" '
            BEGIN {printed=0}
            /^---$/ {if(getline && $0 ~ /^## Latest Autograding Test Results/) {print new_section; printed=1; while(getline && $0 !~ /^## /){}; print; next}}
            {if(!printed) print}
          ' README.md > README.tmp && mv README.tmp README.md
        else
          echo -e "\n$RESULTS_SECTION" >> README.md
        fi
    - name: Commit updated README with replaced test results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Replace README section with latest autograding test results"
        git push